---
title: "RGG Report"
author: ""
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
params:
 toDownload: FALSE
---

```{r setup, include=FALSE}

# knitr R markdown chunk options
knitr::opts_chunk$set(dependson = knitr::all_labels(),
                      echo = FALSE,
                      cache = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      comment = NA,
                      out.width = "100%",
                      error = TRUE)
options(knitr.kable.NA = '')

# loading necessary R packages ####
## data manipulation
library(dplyr)    # %>%, data cleaning functions
library(magrittr) # coerce col to factors or numeric

## outputs - graphs, tables
library(ggplot2)  # ggplot(), etc.
library(plotly)  # ggplot(), etc.
library(DT)       # datatable()
library(knitr)    # kable
library(grafify)
library(data.table)
library(shiny)
```

```{r printfxn, include=FALSE}

# functions ####
# for printing tables (data.frames) - DT::datatable()
printTable <- function(DT, pageLength = 7, 
                       numericColNames = NULL, numRound = 3, ...) {
  
  DT <- data.frame(lapply(X = DT, 
                          FUN = function(x) {
                            if(is.numeric(x)){
                              round(x, numRound)
                            } else {
                              x
                            }
                          }))
  
  table <- DT::datatable(data = DT, 
                         filter = "top", 
                         options = list(autoWidth = TRUE, 
                                        dom = 'l<<t>pB>', 
                                        buttons = c('copy', 'excel'),
                                        pageLength = pageLength,
                                        searchHighlight = TRUE,
                                        lengthMenu = c(7, 14, 21, 28, 35)),
                         extensions = 'Buttons',
                         rownames = FALSE,
                         ...)
  if (length(numericColNames) > 0){
    table <- table %>% formatRound(columns = numericColNames,
                                   digits = numRound)
  }
  
  table
}
```

<!-- END of setup chunk -->

```{r }
suppressWarnings(tryCatch({
  if(file.exists("./outputs/resultRgg.RData")){
    load("./outputs/resultRgg.RData")
  }else{
    load("resultRgg.RData")
  }
}, error = function(e) {
  # NULL
}))

if (is.null(result)){
  # invisible(NULL)
} else {
  
  rggId <- result$status$analysisId[length(result$status$analysisId)]
  mod <- result$modeling %>% filter(analysisId==rggId)
  predsId <- mod[mod$analysisId == rggId & mod$trait == "inputObject","value"]
  pred <- result$predictions %>% filter(analysisId == rggId) # before we use the predsId but now we store the designation predictions in the rgg functions
  met <- result$metrics %>% filter(analysisId==rggId)
  traits <- unique(met$trait)
  ped <- result$data$pedigree
  paramsPed <- result$metadata$pedigree
  colnames(ped) <- cgiarBase::replaceValues(colnames(ped), Search = paramsPed$value, Replace = paramsPed$parameter )
  ped <- unique(ped[,c("designation","yearOfOrigin")])
  # merge yearOfOrigin
  myResult <- merge(pred,ped,by="designation")
  myResult <- myResult[which(!is.na(myResult$yearOfOrigin)),]
}
```

```{r, include=FALSE}
# Init Step to make sure that the dependencies are loaded
htmltools::tagList(printTable(mtcars))
htmltools::tagList(ggplotly(ggplot()))
# Get the current figure size in pixels:
get_w <- function() {
  with(knitr::opts_current$get(c("fig.width", "dpi", "fig.retina")),
       fig.width*dpi/fig.retina)
}

get_h <- function() {
  with(knitr::opts_current$get(c("fig.height", "dpi", "fig.retina")),
       fig.height*dpi/fig.retina)
}
```

## Summary metrics

```{r, results='asis'}
if (is.null(result)){
  # invisible(NULL)
} else {
  
  if("params" %in% ls()){ # we will download the document
    # cat("\n\n## Table       \n\n")
    printTable(met)
    # cat("\n")
  }else{
    h2("Table")
    
    numeric.output <- c("value", "stdError")
    DT::renderDT({DT::formatRound(DT::datatable(met,
                                                rownames = FALSE,
                                                class = 'cell-border stripe',
                                                options = list(
                                                  scrollY = "400px",
                                                  scrollX = "400px",
                                                  paging = F)
    ),numeric.output)
    })
  }
  
}

```

## Regression plot

```{r }
if (is.null(result)){
  # invisible(NULL)
} else {
  
  if("params" %in% ls()){ # we will download the document
    
  }else{
    selectInput(ns("traitSta3"), 
                label = "Trait:", 
                multiple = FALSE,
                choices = unique(traits), 
    )
  }
  
}

```

```{r, results='asis'}
if (is.null(result)){
  # invisible(NULL)
} else {
  
  if("params" %in% ls()){ # we will download the document
    cat("\n\n## Graph {.tabset .tabset-pills}       \n\n")
    
    
    for (j in 1:length(traits)){
      cat("\n\n###", traits[j], "{.tabset .tabset-pills}       \n\n")
      
      # subset by trait
      myPreds <- myResult %>% filter(trait == traits[j])
      myMetrics <- met %>% filter(trait == traits[j])
      myLabel <- paste0("Y = ", round(myMetrics[myMetrics$parameter == "ggInter","value"],4), " + ",
                        round(myMetrics[myMetrics$parameter == "ggSlope","value"],4), " x Year, ", 
                        round(myMetrics[myMetrics$parameter == "gg%","value"],2),"% Gain")
      p <- ggplot(myPreds, aes(x=as.factor(yearOfOrigin), y=predictedValue)) + 
        geom_violin(trim=FALSE, fill="gray")+
        labs(title=myLabel,x="Year of origin", y = "Trait performance")+
        geom_boxplot(width=0.1)#+theme_classic()
      print(htmltools::tagList(plotly::ggplotly(p)))
      
      # cat("\n")
    }
    
    cat("\n")
  }else{ # regular rendering
    plotly::renderPlotly({
      myPreds <- myResult %>% filter(trait == input$traitSta3)
      myMetrics <- met %>% filter(trait == input$traitSta3)
      myLabel <- paste0("Y = ", round(myMetrics[myMetrics$parameter == "ggInter","value"],4), " + ",
                        round(myMetrics[myMetrics$parameter == "ggSlope","value"],4), " x Year, ", 
                        round(myMetrics[myMetrics$parameter == "gg%","value"],2),"% Gain")
      p <- ggplot(myPreds, aes(x=as.factor(yearOfOrigin), y=predictedValue)) + 
        geom_violin(trim=FALSE, fill="gray")+
        labs(title=myLabel,x="Year of origin", y = "Trait performance")+
        geom_boxplot(width=0.1) # + theme_classic()
      fig <-  plotly::ggplotly(p)#, height = get_h()*2);
      fig
    })
  }
  
}

```
