---
title: "STA Report"
author: ""
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  rmdformats::robobook:
  # html_document:
  # toc: TRUE
  toc_depth: 4
# runtime: shiny
---

<style>
.main-container {
  max-width: 200%;
  margin-left: 0;
  margin-right: 0;
}
.tab-content {
  margin-bottom: 50px;
}
.book .book-body .page-inner {
  max-width: 2000px;
}
</style>

```{r setup, include=FALSE}

# knitr R markdown chunk options
knitr::opts_chunk$set(dependson = knitr::all_labels(),
                      echo = FALSE,
                      cache = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      comment = NA,
                      out.width = "100%",
                      error = TRUE)
options(knitr.kable.NA = '')

# loading necessary R packages ####
## data manipulation
library(dplyr)    # %>%, data cleaning functions
library(magrittr) # coerce col to factors or numeric

## outputs - graphs, tables
library(ggplot2)  # ggplot(), etc.
library(plotly)  # ggplot(), etc.
library(DT)       # datatable()
library(knitr)    # kable
library(data.table)
library(shiny)
```
<!-- END of setup chunk -->

```{r printfxn, include=FALSE}

# functions ####
# for printing tables (data.frames) - DT::datatable()
printTable <- function(DT, pageLength = 7, 
                       numericColNames = NULL, numRound = 3, ...) {
  
  DT <- data.frame(lapply(X = DT, 
                          FUN = function(x) {
                            if(is.numeric(x)){
                              round(x, numRound)
                            } else {
                              x
                            }
                          }))
  
  table <- DT::datatable(data = DT, 
                         filter = "top", 
                         options = list(autoWidth = TRUE, 
                                        dom = 'l<<t>pB>', 
                                        buttons = c('copy', 'excel'),
                                        pageLength = pageLength,
                                        searchHighlight = TRUE,
                                        lengthMenu = c(7, 14, 21, 28, 35)),
                         extensions = 'Buttons',
                         rownames = FALSE,
                         ...)
  if (length(numericColNames) > 0){
    table <- table %>% formatRound(columns = numericColNames,
                                   digits = numRound)
  }
  
  table
}
```
<!-- END of printfxn chunk -->

```{r, results='asis'}
suppressWarnings(tryCatch({
  load("./outputs/resultSta.RData")
}, error = function(e) {
  NULL
}))
if (is.null(result)){
  invisible(NULL)
} else {
  
  cat("\n\n## Entries and traits by environment     \n")

  cat("\n\n The following table allows to see which locations had data for the different traits.   \n")
  
  pred <- result$predictions
  traits <- unique(pred$trait)
  traits.env <- aggregate(designation ~ environment + trait, data = pred, FUN = length)
  traits.env <- reshape(data=traits.env, timevar = "trait", idvar = "environment", direction="wide")
  colnames(traits.env) <- c('environment',traits)
  
  summarySta <- as.data.frame(traits.env[,'environment'])
  for (i in 1:length(traits)){
    temp <- traits.env[,c('environment',traits[i])]
    colnames(temp)[2] <- "temp.col"
    temp <- as.data.frame(temp)
    j=i+1
    tempp=within(temp,{
      temp.col.n=NA
      temp.col.n[!is.na(temp.col)]='✅ '
      temp.col.n[is.na(temp.col)]=''
    })
    temp <- tempp[,3]
    summarySta <- cbind(summarySta,temp)
  }
  colnames(summarySta) <- c('environment',traits)
  
  pheno <- result$data$pheno
  pheno.env <- pheno[,c('environment','designation')]
  pheno.env<- unique(pheno.env[c('designation','environment')]) 
  pheno.env.designation <-  aggregate(designation ~environment, data = pheno.env, FUN = length)
  colnames(pheno.env.designation)[2] <- "# of entries"
  
  summarySta <- merge(x = summarySta, y = pheno.env.designation, by = "environment", all = TRUE)
  summarySta <- kableExtra::kbl(summarySta)
  summarySta <-kableExtra::kable_styling(
    summarySta, 
    bootstrap_options = c("hover","condensed","responsive"), fixed_thead = T)
  kableExtra::scroll_box(summarySta,width = "100%")
}
```


```{r }
if (is.null(result)){
  invisible(NULL)
} else {
  modeling <- result$modeling
  idSta <- result$status[which(result$status$module == "sta"),"analysisId"];
  idSta <- idSta[length(idSta)]
  modeling <- modeling[which(modeling$analysisId == idSta),"trait"]
}

```

```{r, include=FALSE}
# Init Step to make sure that the dependencies are loaded
htmltools::tagList(printTable(result$modeling))
htmltools::tagList(ggplotly(ggplot()))
```

```{r summarySTA, echo = F, message = FALSE, warning = FALSE, results='asis'}
if (is.null(result)){
  invisible(NULL)
} else {
  
  cat("\n\n## Summary statistics       \n\n")

  cat("\n\n The following table allows you to verify different quality metrics (KPIs) for the different environments. The selector button allows you to filter by trait.       \n\n")
  
  pred.traits <- subset(pred, select = c(trait,designation,environment,predictedValue))
  pred.traits <- reshape(
    data=pred.traits, 
    timevar = c("trait"), 
    idvar = c("environment","designation"), 
    direction="wide"
  )
  names(pred.traits)[-c(1,2)] <- gsub("predictedValue.", "", names(pred.traits)[-c(1,2)]) 
  pred.traits <- reshape(pred.traits, 
                         direction = "long",
                         varying = list(names(pred.traits)[3:ncol(pred.traits)]),
                         v.names = "Value",
                         idvar = c("designation", "environment"),
                         timevar = "trait",
                         times = traits)
  rownames(pred.traits) <- NULL
  ## Max
  pred.traits.max <- aggregate(Value ~ environment + trait, data = pred.traits, function(x) max(x,na.rm=T))
  colnames(pred.traits.max)[3] <- "max"
  ## Min
  pred.traits.min <- aggregate(Value ~ environment + trait, data = pred.traits, function(x) min(x,na.rm=T))
  colnames(pred.traits.min)[3] <- "min"
  ## Mean
  pred.traits.mean <- aggregate(Value ~ environment + trait, data = pred.traits, function(x) mean(x,na.rm=T))
  colnames(pred.traits.mean)[3] <- "mean"
  ## H2
  metrics <- result$metrics
  metrics.h2 <- metrics[metrics$parameter=="plotH2",]
  metrics.h2 <- subset(metrics.h2, select = c(trait,environment,value))
  colnames(metrics.h2)[3] <- "H2"
  ## CV
  metrics.CV <- metrics[metrics$parameter=="CV",]
  metrics.CV <- subset(metrics.CV, select = c(trait,environment,value))
  colnames(metrics.CV)[3] <- "CV"
  ## r2
  metrics.r2 <- metrics[metrics$parameter=="r2",]
  metrics.r2 <- subset(metrics.r2, select = c(trait,environment,value))
  colnames(metrics.r2)[3] <- "r2"
  ## Vg
  metrics.Vg <- metrics[metrics$parameter=="Vg",]
  metrics.Vg <- subset(metrics.Vg, select = c(trait,environment,value))
  colnames(metrics.Vg)[3] <- "Vg"
  ## Vr
  metrics.Vr <- metrics[metrics$parameter=="Vr",]
  metrics.Vr <- subset(metrics.Vr, select = c(trait,environment,value))
  colnames(metrics.Vr)[3] <- "Vr"
  
  pred.traits.summary <- merge(x = pred.traits.min, y = pred.traits.mean, by = c("environment","trait"), all = TRUE)
  pred.traits.summary <- merge(x = pred.traits.summary, y = pred.traits.max, by = c("environment","trait"), all = TRUE)
  pred.traits.summary <- merge(x = pred.traits.summary, y = metrics.h2, by = c("environment","trait"), all = TRUE)
  pred.traits.summary <- merge(x = pred.traits.summary, y = metrics.CV, by = c("environment","trait"), all = TRUE)
  pred.traits.summary <- merge(x = pred.traits.summary, y = metrics.r2, by = c("environment","trait"), all = TRUE)
  pred.traits.summary <- merge(x = pred.traits.summary, y = metrics.Vg, by = c("environment","trait"), all = TRUE)
  pred.traits.summary <- merge(x = pred.traits.summary, y = metrics.Vr, by = c("environment","trait"), all = TRUE)

  printTable(pred.traits.summary)
 # print(htmltools::tagList(printTable(pred.traits.summary)))
  
}
```


```{r }
if (is.null(result)){
  invisible(NULL)
} else {
  modeling <- result$modeling
  idSta <- result$status[which(result$status$module == "sta"),"analysisId"];
  idSta <- idSta[length(idSta)]
  envs <- unique(result$predictions[which( result$predictions$analysisId == idSta),"environment"])
}

```


```{r predictions, echo = F, message = FALSE, warning = FALSE, results='asis'}
if (is.null(result)){
  invisible(NULL)
} else {
  
  cat("\n\n## Predictions       \n\n")

  cat("\n\n The following table allows you to check the trait predictions in wide format and filter them by environment.       \n\n")
  
  traits <- unique(pred$trait)
  predictions.designation <- subset(pred, select = c(trait,designation,environment,predictedValue))
  predictions.designation <- reshape(
    data=predictions.designation, 
    timevar = c("trait"), 
    idvar = c("environment","designation"), 
    direction="wide"
  )
  names(predictions.designation) <- c("designation","environment",traits)
  
  printTable(predictions.designation)
 # print(htmltools::tagList(printTable(predictions.designation)))
}

```


```{r }
if (is.null(result)){
  invisible(NULL)
} else {
  modeling <- result$modeling
  idSta <- result$status[which(result$status$module == "sta"),"analysisId"];
  idSta <- idSta[length(idSta)]
  modeling <- modeling[which(modeling$analysisId == idSta),"trait"]
  traits <- unique(modeling)
}

```

```{r myBoxplot, echo = F, message = FALSE, warning = FALSE, results='asis'}
get_h <- function() {
  with(knitr::opts_current$get(c("fig.height", "dpi", "fig.retina")),
       fig.height*dpi/fig.retina)
}

predTrait <- result$predictions

cat("\n\n## Boxplot {.tabset .tabset-pills}       \n\n")
cat("\n\n The following boxplot allows you to see the distribution of predicted values by trait in the different environments.       \n\n")

  for (j in 1:length(traits)){
    cat("\n\n###", traits[j], "{.tabset .tabset-pills}       \n\n")
      
      p <- ggplot2::ggplot(predTrait[which(predTrait$trait %in% traits[j]),], ggplot2::aes(x=environment, y=predictedValue, label=designation) ) + 
      ggplot2::geom_jitter(position=ggplot2::position_jitter(width=0.3, height=0.2), ggplot2::aes(colour=environment), alpha=0.9) +
      # ggplot2::geom_boxplot(alpha = 0.5, show.legend = FALSE, ggplot2::aes(fill=factor(environment))) +
      ggplot2::theme(strip.text.x = ggplot2::element_text(size=9, color="black", face="bold"), 
                     axis.text.x = ggplot2::element_text(angle = 45), legend.position = "none") +
      ggplot2::labs(x="", y="Trait value") + ggplot2::facet_grid(trait~., scales = "free") #+
    # ggplot2::guides(color=ggplot2::guide_legend("Environment"))
    
    # fig2 <-  plotly::ggplotly(p)#, height = get_h()*2); # fig2
    # fig2
    print(htmltools::tagList(ggplotly(p)))
      
      cat("\n")
    }
  
  cat("\n")

```
