---
title: "RGG Report"
author: ""
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  rmdformats::robobook:
  # html_document:
  # toc: TRUE
  toc_depth: 4
# runtime: shiny
---

<style>
.main-container {
  max-width: 200%;
  margin-left: 0;
  margin-right: 0;
}
.tab-content {
  margin-bottom: 50px;
}
.book .book-body .page-inner {
  max-width: 2000px;
}
</style>

```{r setup, include=FALSE}

# knitr R markdown chunk options
knitr::opts_chunk$set(dependson = knitr::all_labels(),
                      echo = FALSE,
                      cache = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      comment = NA,
                      out.width = "100%",
                      error = TRUE)
options(knitr.kable.NA = '')

# loading necessary R packages ####
## data manipulation
library(dplyr)    # %>%, data cleaning functions
library(magrittr) # coerce col to factors or numeric

## outputs - graphs, tables
library(ggplot2)  # ggplot(), etc.
library(plotly)  # ggplot(), etc.
library(DT)       # datatable()
library(knitr)    # kable
library(grafify)
library(data.table)
library(shiny)
```
<!-- END of setup chunk -->

```{r printfxn, include=FALSE}

# functions ####
# for printing tables (data.frames) - DT::datatable()
printTable <- function(DT, pageLength = 7, 
                       numericColNames = NULL, numRound = 3, ...) {
  
  DT <- data.frame(lapply(X = DT, 
                          FUN = function(x) {
                            if(is.numeric(x)){
                              round(x, numRound)
                            } else {
                              x
                            }
                          }))
  
  table <- DT::datatable(data = DT, 
                         filter = "top", 
                         options = list(autoWidth = TRUE, 
                                        dom = 'l<<t>pB>', 
                                        buttons = c('copy', 'excel'),
                                        pageLength = pageLength,
                                        searchHighlight = TRUE,
                                        lengthMenu = c(7, 14, 21, 28, 35)),
                         extensions = 'Buttons',
                         rownames = FALSE,
                         ...)
  if (length(numericColNames) > 0){
    table <- table %>% formatRound(columns = numericColNames,
                                   digits = numRound)
  }
  
  table
}
```
<!-- END of printfxn chunk -->

```{r }
suppressWarnings(tryCatch({
        load("./outputs/resultRgg.RData")
      }, error = function(e) {
        NULL
      }))
if (is.null(result)){
  invisible(NULL)
} else {
  pred <- result$predictions %>% filter(module == "mta")
  met <- result$metrics %>% filter(module == "rgg", trait != "desireIndex")
  traits <- unique(met$trait)
  ped <- result$data$pedigree
}
```

```{r, include=FALSE}
# Init Step to make sure that the dependencies are loaded
htmltools::tagList(printTable(met))
htmltools::tagList(ggplotly(ggplot()))
```

```{r geneticGain, echo = F, message = FALSE, warning = FALSE, results='asis'}

# fxn for generating genetic gain

gg <- function(data, label = NULL, title = NULL, trait) {
  
  data$genoYearOriginBase <- as.numeric(data$yearOfOrigin) - min(as.numeric(data$yearOfOrigin))
  
  # fit the model
  ggfit.lm <- lm(predictedValue ~ genoYearOriginBase, data = data)
  ggfit.sum <- summary(ggfit.lm)

  tmpGGData <- data.frame(data, 
                          Intercept = ggfit.sum$coefficients[1,1], 
                          Slope = ggfit.sum$coefficients[2,1])
  tmpGGData$yearOfOrigin <- as.numeric(tmpGGData$yearOfOrigin)
  
  # graph
  
  mylabel <- ifelse(ggfit.sum$coefficients[2,1] > 0, 
                      paste0("Y = ", round(ggfit.sum$coefficients[1,1],4), " + ",
                             round(ggfit.sum$coefficients[2,1],4), " x Year, ", 
                             round((ggfit.sum$coefficients[2,1]/ggfit.sum$coefficients[1,1])*100,2),"% Gain"),
                      paste0("Y = ", round(ggfit.sum$coefficients[1,1],6), " - ",  
                             abs(round(ggfit.sum$coefficients[2,1],4)), " x Year, ", 
                             round((ggfit.sum$coefficients[2,1]/ggfit.sum$coefficients[1,1])*100,2),"% Gain"))
  
  labelInterval <- ifelse(max(unique(tmpGGData$yearOfOrigin))- min(unique(tmpGGData$yearOfOrigin)) 
                          > 10, 5, 2)
  
  xlabel <- seq(min(unique(tmpGGData$yearOfOrigin)), max(unique(tmpGGData$yearOfOrigin)), 
                by = labelInterval)
  
  xbreak <- xlabel - min(xlabel)
  
  myplot <- ggplot(data = tmpGGData,
                   aes(x = genoYearOriginBase, y = predictedValue,
                       ymin = predictedValue - stdError ,
                       ymax = predictedValue + stdError)) +
    geom_point(color = 'darkgreen') +
    # geom_errorbar() +
    geom_segment(aes(x = min(genoYearOriginBase),
                     xend = max(genoYearOriginBase),
                     y = Intercept + Slope,
                     yend = Intercept + Slope*max(genoYearOriginBase)),
                 color = "red") +
    labs(x = "Year of Origin", y = trait, title = mylabel) + 
    # annotate("text", label=strong(italic(mylabel)), x = min(tmpGGData$genoYearOriginBase) + 1, 
    #          y = max(tmpGGData$predictedValue) + 1,
    #          color="black", size=4, fontface = "bold.italic") +
    theme(plot.caption = element_text(hjust = 0, face = "italic")) +
    scale_x_continuous(breaks = xbreak, labels = xlabel)
  
  print(htmltools::tagList(ggplotly(myplot)))
}

```

```{r geneticGainData2, echo = F, message = FALSE, warning = FALSE, results='asis'}
if (is.null(result)){
  invisible(NULL)
} else {
  cat("\n\n## Table       \n\n")

  print(htmltools::tagList(printTable(met)))
  
  cat("\n")
}

```

```{r geneticGainData3, echo = F, message = FALSE, warning = FALSE, results='asis'}
if (is.null(result)){
  invisible(NULL)
} else {
  cat("\n\n## Graph {.tabset .tabset-pills}       \n\n")

  # merge yearOfOrigin
  myResult <- merge(pred,ped,by="designation")

  for (j in 1:length(traits)){
    cat("\n\n###", traits[j], "{.tabset .tabset-pills}       \n\n")
      
      # subset by trait
      myMETPred <- myResult %>% filter(trait == traits[j])
      myresult1 <- gg(data = myMETPred, trait = traits[j])
      
      cat("\n")
    }
  
  cat("\n")
}
  
```
